feat: add sample countdown trial that counts down before the start of…
brown-ccv/honeycomb pull request #496
Opened 2024-06-19 03:25 UTC by YUUU23

- add example `countdown` trial in `trials` folder inside honeycomb for counting down given millisecond (ms) before another trial begins: 
  - in `src/experiment/trials/countdown.js`: 
       - helper functions to convert ms to minutes and seconds to format a time string (00:00) 
       - `buildCountdownTrial` function to return the actual JS trial object that counts down and updates the time string every few ms until counted down to 0 
   - in `src/experiment/honeycomb.js`: an example usage of the `countdown` trial to countdown 6000ms and inserted in the experiment timeline

2024-06-24 14:22 UTC, RobertGemmaJr requested changes
Let's chat about this a little closer on Tuesday? We have a special utils file in the lib/ folder that I think some of these functions would work perfectly! Love the way they're broken out and a little renaming would make them perfect for the entire project!

Fantastic work 🙌

2024-06-24 14:22 UTC, RobertGemmaJr commented on src/experiment/trials/countdown.js
> +  const waitTime = ms;
I would rename the parameter here to be `waitTime` instead of `ms`! You note that the time is in milliseconds in the docstring and that's the most common way time is handled in JS so you can be a little more explicit with the variable name of the function

2024-06-24 14:22 UTC, RobertGemmaJr commented on src/experiment/trials/countdown.js
> + * @param {*} ms - millisecond
Can you update the types here? It looks like they're almost always a `number`

```suggestion
 * @param {number} ms - millisecond
```

2024-06-24 14:22 UTC, RobertGemmaJr commented on src/experiment/honeycomb.js
> +  const countdownTrial = buildCountdownTrial(6000);
Let's make this 3000? Just so it's not taking up too much time

2024-06-24 18:48 UTC, YUUU23 commented
@RobertGemmaJr Thank you for these feedbacks! I will go ahead and make those changes, and let's talk about it more on Tuesday's meeting! : )

2024-06-26 03:48 UTC, YUUU23 reviewed
All changes discussed about should be changed!

2024-06-26 14:19 UTC, RobertGemmaJr approved these changes
Wonderful! Thank you for this!

2024-06-26 14:19 UTC, RobertGemmaJr commented on src/experiment/trials/countdown.js
> +}
This can be moved into `src/lib/utils`!

2024-06-26 14:19 UTC, RobertGemmaJr commented on src/experiment/trials/countdown.js
> +}
This can be moved into `sec/lib/utils`!

2024-06-26 14:20 UTC, RobertGemmaJr commented
@YUUU23 You can actually merge this pull request into `3.4.1`! Sorry if that was confusing

2024-06-26 18:36 UTC, merged