Add num blinks
brown-ccv/honeycomb pull request #526
Opened 2024-08-04 17:18 UTC by YUUU23

- add `code` and `numBlinks` as nested object to each event code
- modify how even names and code are accessed to reflect the change in object structure 
- change `eventCodes` import in `trigger.js` to be more concise

2024-08-12 15:26 UTC, eldu requested changes
Looks great! A few typos and some questions here

Where are `numBlinks` being used? It looks like we're just setting it right now

2024-08-12 15:26 UTC, eldu commented on src/config/eventCodes.json
> +    "numbBlinks": 1
typo

```suggestion
    "numBlinks": 1
```

2024-08-12 15:26 UTC, eldu commented on src/config/eventCodes.json
> +    "numbBlinks": 18
typo

```suggestion
    "numBlinks": 18
```

2024-08-12 15:26 UTC, eldu commented on src/config/eventCodes.json
> +    "numbBlinks": 32
typo

```suggestion
    "numBlinks": 32
```

2024-08-13 04:25 UTC, YUUU23 commented
> Looks great! A few typos and some questions here
> 
> Where are `numBlinks` being used? It looks like we're just setting it right now

I am actually not entirely sure of this; it seems like the most relevant case I found is here: [src/lib/markup/photodiode.js](https://github.com/brown-ccv/honeycomb/blob/922ab5370ef9ea487808d23f076d44a2a8ffc038/src/lib/markup/photodiode.js#L32), we set a `blinkTime`. However, I'm not sure what's the purpose for all eventCodes to have a blink time that is the same as their code.

2024-08-13 14:35 UTC, eldu reviewed
I think this PR needs @RobertGemmaJr to approve since I don't think I understand the configuration enough to give the okay 😓

2024-08-13 14:35 UTC, eldu commented on src/config/eventCodes.json
> +    "numBlinks": 1
If the numBlinks should be the same as the code, then this should be `2`?

I feel like this might be a Rob question at this point 😵

2024-08-14 19:39 UTC, YUUU23 commented
> I think this PR needs @RobertGemmaJr to approve since I don't think I understand the configuration enough to give the okay 😓

Sounds good! I can wait until Rob comes back to discuss more about this. Thank you for reviewing it so far : D !

2024-08-14 19:41 UTC, YUUU23 commented on src/config/eventCodes.json
> +    "numBlinks": 1
Yes, this is my mistake without taking a closer look. Let me make this change to make things more uniform and wait for Rob to review the rest.

2024-08-20 20:13 UTC, RobertGemmaJr reviewed
This looks super great! Why don't we move the `code` and `numbBlinks` for each trial type into their trial in the `settings.json` file. This way we can delete the `eventCodes.json` file for some consolidation! All of the values look great!

2024-08-21 20:34 UTC, YUUU23 commented on src/Electron/main.js
> + * @param {Object} trigger.settings The list of possible event with relative event codes to be triggered
since codes are now embedded under the settings.json, I had to import the entire settings object into the trigger object to access the code

2024-08-21 20:35 UTC, YUUU23 commented on src/config/settings.json
> +  "open_task": {
inserted these 2 events from the original event codes file

2024-08-21 20:38 UTC, YUUU23 commented on src/experiment/procedures/honeycombProcedure.js
> +      code: honeycombSettings.code,
since `honeycombSettings` is set to `settings.honeycomb`, we can directly access the `code` field

2024-08-22 13:14 UTC, RobertGemmaJr approved these changes
Looks great! I think eventually I will move all of the trigger stuff into the settings file but should be done in another PR. This looks fantastic! 🚀

2024-08-22 13:14 UTC, RobertGemmaJr commented on src/experiment/procedures/honeycombProcedure.js
>      },
Just removing a console log
```suggestion
      if (ENV.USE_PHOTODIODE) pdSpotEncode(honeycombSettings.code);
    },
```

2024-08-22 15:17 UTC, eldu approved these changes

2024-08-22 19:56 UTC, merged